Enhancement/start booklet after login
iqb-berlin/testcenter pull request #301
Opened 2023-05-23 10:49 UTC by huaning-yang

Resolves #259

2023-05-23 13:13 UTC, paflov commented
Ja, es gibt noch [das Anmelde-Verfahren mittels Link](https://github.com/iqb-berlin/iqb-berlin.github.io/wiki/Login-Anmeldeverfahren#noch-k%C3%BCrzer-link). Vielleicht kannst du noch mal testen, ob es dort auch funktioniert.

2023-05-26 09:30 UTC, paflov requested changes

2023-06-08 07:58 UTC, huaning-yang commented on frontend/src/app/app-route-guards.ts
> +          if(authData.claims.test.length == 1 && this.router.getCurrentNavigation().extras.skipLocationChange == false){
Der derzeitige Ansatz klappt vermutlich nicht.
Wenn ich an dieser Stelle nur auf einen Test prüfe, dann geht das Routing kaputt. Wenn man zB als normaler Testtaker nur einen Test hat und ihn dann beenden möchte, dann bleibt man auf der Seite stecken. 
Also vermutlich müsste ich das an anderer Stelle einbauen oder gibt es ein anderes Herausstellungsmerkmal was nur das Anmeldeverfahren per Link hat?

2023-06-12 07:40 UTC, paflov commented on frontend/src/app/app-route-guards.ts
> +          if(authData.claims.test.length == 1 && this.router.getCurrentNavigation().extras.skipLocationChange == false){
Ich glaube wir reden aneinander vorbei? Eventuell mal zoomen?

2023-06-15 10:30 UTC, huaning-yang commented
Ich habe mit meinem letzten Commit eine Möglichkeit gefunden Login per Link zu unterscheiden.
Die Unterscheidung ist allerdings nur möglich unter der Annahme dass man sich nicht auf dem Testcenter befindet.
Wenn man von einer anderen Webseite kommt, dann ist der Wert getCurrentNavigation.previousNavigation = null.
Diese Eigenschaft zusammen mit claims.test.length= 1 und claims.test ist das einzige Element in claims sollte dann den Fall (Login per Link mit nur einem Booklet) beschreiben, zumindest ist mir bei meinen Tests sonst nichts aufgefallen. Und für die beiden Button Test fortsetzen/Test beenden konnte ich mit dieser Unterscheidung auch keinen Funktionsverlust feststellen, so wie es vorher der Fall war.
Wenn man sich bereits auf dem Testcenter befindet und dann sich per Link anmelden will, wird man zum normalen Teststarter geleitet, weil ich da sonst keine Methode gefunden habe es zu unterscheiden.

An sich denke ich, dass das ausreichen sollte. Da solche Links zum direkten Anmelden wahrscheinlich über Emails verteilt werden, man sich also nicht auf der Testcenter Seite befindet wenn man dieses Verfahren benutzt.
Den angemerkten Fehler mit den Group-Monitors sollte ebenfalls behoben sein.

2023-06-26 12:26 UTC, merged