Enhancement/multi select accessrights
iqb-berlin/testcenter pull request #327
Opened 2023-08-09 12:42 UTC by huaning-yang

Resolves #300.
Außerdem könnte das #8 ebenfalls resolven.
Ich habe mich bewusst dafür entschieden, die Buttons erst mal nur für den workspace Bereich zu ändern, damit man noch den Vergleich im Admins Bereich hat.
Wenn die Buttons so in Ordnung aussehen, dann würde ich das natürlich auch für den Admins Bereich ändern.

2023-08-21 07:16 UTC, paflov commented
Ich übergebe das Review mal an Richrad, da das seine Tickets waren.

2023-08-21 10:21 UTC, paflov commented
Wenn er zufrieden ist, kannst du es auf die Admins übertragen. Und würde ich noch um einen pathetischen Satz im changelog bitten ;)

2023-08-28 09:59 UTC, rhenck commented
Also ich bekomme den Branch nicht zum Laufen.

Beim Starten erscheint folgendes:

> testcenter-frontend              | Warning: /app/src/app/app-root/login/login.component.ts depends on 'ua-parser-js'. CommonJS or AMD dependencies can cause optimization bailouts.
testcenter-frontend              | For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
testcenter-frontend              | 
testcenter-frontend              | 
testcenter-frontend              | 
testcenter-frontend              | ./src/app/app-root/login/login.component.ts:2:0-51 - Error: Module not found: Error: Can't resolve 'browserslist-useragent' in '/app/src/app/app-root/login'
testcenter-frontend              | 
testcenter-frontend              | Error: src/app/app-root/login/login.component.ts:5:27 - error TS2307: Cannot find module 'browserslist-useragent' or its corresponding type declarations.
testcenter-frontend              | 
testcenter-frontend              | 5 import { matchesUA } from 'browserslist-useragent';


Und wenn ich neu bauen will dieses:

> #0 21.84 Error: src/app/app-root/login/login.component.ts:5:27 - error TS7016: Could not find a declaration file for module 'browserslist-useragent'. '/app/node_modules/browserslist-useragent/lib/index.js' implicitly has an 'any' type.
#0 21.84   Try `npm i --save-dev @types/browserslist-useragent` if it exists or add a new declaration (.d.ts) file containing `declare module 'browserslist-useragent';`
#0 21.84 
#0 21.84 5 import { matchesUA } from 'browserslist-useragent';
#0 21.84                             ~~~~~~~~~~~~~~~~~~~~~~~~
#0 21.84 
#0 21.84 
#0 21.84 Error: src/app/test-controller/services/test-loader.service.ts:118:43 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
#0 21.84   Type 'undefined' is not assignable to type 'string'.
#0 21.84 
#0 21.84 118       this.tcs.maxTimeTimers = JSON.parse(lastState[TestStateKey.TESTLETS_TIMELEFT]);
#0 21.84                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#0 21.84 
#0 21.84 
#0 21.84 Error: src/app/test-controller/services/test-loader.service.ts:121:47 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
#0 21.84   Type 'undefined' is not assignable to type 'string'.
#0 21.84 
#0 21.84 121       this.tcs.clearCodeTestlets = JSON.parse(lastState[TestStateKey.TESTLETS_CLEARED_CODE]);
#0 21.84                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ich weiss nicht so recht, wie ich damit umgehen soll. Habt ihr eine Idee?

2023-08-28 10:12 UTC, paflov commented
Node module updaten. lokalen frontend/node_modules und image neubauen.

2023-08-28 10:14 UTC, rhenck requested changes

2023-08-28 10:14 UTC, rhenck commented on frontend/src/app/superadmin/users/users.component.html
> -                        (change)="$event ? tableselectionCheckbox.toggle(row) : null"
Auch wenn man an einer anderen Sache arbeitet, kann man ruhig mal links und rechts gucken und den Code verbessern. Die Konstruktion ("$event ? tableselectionCheckbox.toggle(row) : null"), an die du dich hier rangehangen hast ist äußerst fragwürdig und die hätte ich bei der Gelegenheit mal überarbeitet.

Ungeachtet der Qualität der Lösung, scheint es hier doch bereits Logik zu geben. Warum integriest du das neue nicht darin, sondern baust zusätzliche Dinge? Aber ich finde den Code generell schwer verständlich. Vllt telefonieren wir hierzu mal und du erklärst mir, was da passiert.

2023-08-28 10:14 UTC, rhenck commented on frontend/src/app/superadmin/workspaces/workspaces.component.ts
> +        this.selectedRows.splice(indexRow,1);
Fehlendes Leerzeichen. Hinter Kommas kommen immer Leerzeichen. Schade, dass der Linter da nicht meckert.

2023-08-28 10:25 UTC, rhenck commented
> Node module updaten. lokalen frontend/node_modules und image neubauen.

Okay hab mal alles weggehauen und neu gebaut. Nun gehts. Danke

2023-08-28 10:26 UTC, rhenck commented
![image](https://github.com/iqb-berlin/testcenter/assets/446878/899251c2-5732-400b-97de-4646cea5bf78)

Sieht bei mir so aus.

2023-08-28 10:30 UTC, rhenck commented
Irgendwie scheinen mir ToggleButtons nicht der richtige Ansatz zu sein. Wir haben ja 3 mögliche Zustände: kein Zugriff; Lesen; Lesen+Schreiben. Mit dieser Lösung, kann ich "kein Zugriff" nicht mehr bewerkstelligen. Oder habe ich da was übersehen?

2023-08-28 10:50 UTC, paflov commented
> Irgendwie scheinen mir ToggleButtons nicht der richtige Ansatz zu sein. Wir haben ja 3 mögliche Zustände: kein Zugriff; Lesen; Lesen+Schreiben. Mit dieser Lösung, kann ich "kein Zugriff" nicht mehr bewerkstelligen. Oder habe ich da was übersehen?

Stimmt (hatte selber noch nicht reingeschaut vorher).

2023-08-28 11:37 UTC, rhenck commented
> > Irgendwie scheinen mir ToggleButtons nicht der richtige Ansatz zu sein. Wir haben ja 3 mögliche Zustände: kein Zugriff; Lesen; Lesen+Schreiben. Mit dieser Lösung, kann ich "kein Zugriff" nicht mehr bewerkstelligen. Oder habe ich da was übersehen?
> 
> Stimmt (hatte selber noch nicht reingeschaut vorher).

Also ich sehe 2,5 Möglichkeiten:
1: ToggleButtons behalten, aber dann halt mit 3 Optionen
1b: klassisch mit DropDown und den 3 Varianten
2: Wir behalten Checkboxen. Aber dann gibt es eine für Lesen und eine für Schreiben. Und wenn man Schreiben auswählt, setzt sich Lesen automatisch mit. In etwa wie auf folgendem Bild:
https://docs.plesk.com/en-US/obsidian/customer-guide/images/80279.webp

2023-08-28 11:40 UTC, rhenck commented
Bei der Gelegenheit könnte man auch überlegen, ob ein unbedarfter Benutzer überhaupt eine Ahnung hat was sich hinter "RO" und "RW" verbirgt. Das könnte man vllt auch ausschreiben, wenigstens aber Tooltips dranpacken.

2023-08-28 11:59 UTC, paflov commented
Hat Huaning das Ticket #300 denn zu deiner Zufriedenheit gelöst?

2023-08-28 12:25 UTC, rhenck commented
> Hat Huaning das Ticket #300 denn zu deiner Zufriedenheit gelöst?

Jein. Die Zeilenauswahl ist weg und dadurch ist etwas Verwirrung vermieden. Allerdings finde ich es etwas unbequem, dass man nun immer in die Checkbox klicken muss. Ich würde es so lösen, dass das Auswählen einer Zeile automatisch die Checkbox mitsetzt.

Das Problem was nun enstanden ist, ist dass man mehrere Zeilen auswählt (anhakt) und dann rechts Berechtigungen erscheinen, die uneindeutig sind. Er zeigt im Moment einfach die an, die man zuletzt angeklickt hat.
Ist kein triviales Problem, aber er dürfte nicht so tun, als hätten alle Zeilen die gleichen Werte, wenn dem nicht so ist.
Hoffe das ist verständlich, fällt mir gerade schwer das klar auszudrücken.

2023-08-28 12:26 UTC, paflov commented
> > Hat Huaning das Ticket #300 denn zu deiner Zufriedenheit gelöst?
> 
> Jein. Die Zeilenauswahl ist weg und dadurch ist etwas Verwirrung vermieden. Allerdings finde ich es etwas unbequem, dass man nun immer in die Checkbox klicken muss. Ich würde es so lösen, dass das Auswählen einer Zeile automatisch die Checkbox mitsetzt.
> 
> Das Problem was nun enstanden ist, ist dass man mehrere Zeilen auswählt (anhakt) und dann rechts Berechtigungen erscheinen, die potentiell uneindeutig sind. Er zeigt im Moment einfach die an, die man zuletzt angeklickt hat. Ist kein triviales Problem, aber er dürfte nicht so tun, als hätten alle Zeilen die gleichen Werte, wenn dem nicht so ist. Hoffe das ist verständlich, fällt mir gerade schwer das klar auszudrücken.

Also ich verstehs, aber klärt das mal miteinander :)

2023-08-28 14:57 UTC, huaning-yang commented
Ich verstehe auch was das Problem ist. 
Werde Versuchen die oben genannten Änderungen umzusetzen und den Ansatz nochmal etwas überdenken

2023-10-19 11:27 UTC, closed without merging