fe: Remove multi-select from superadmin view
iqb-berlin/testcenter pull request #370
Opened 2023-10-19 12:09 UTC by huaning-yang

Wie heute besprochen habe ich die Checkbox für die Mechfachauswahl im Admin und Arbeitsbereich vom Superadmin entfernt.

2023-11-22 08:46 UTC, paflov commented
Bitte prüfe einmal händisch, ob die e2e tests noch laufen und passe die ggf an. In der CI funktionieren sie leider z.Z. nicht.

2023-11-22 08:47 UTC, paflov commented
Ich habe den Branch außerdem mal mit dem aktuellen master synchronisiert, weil die init-tests fehlschlugen und das auf dem Master bereits gefixed sein sollte.

2023-11-28 16:19 UTC, rhenck requested changes

2023-11-28 16:19 UTC, rhenck commented on frontend/src/app/superadmin/users/users.component.ts
> -    let selectedRows = this.tableselectionCheckbox.selected;
Funktioniert dein Linter? Hier meckert er (zurecht) bei mir:
"ESLint: 'selectedRows' is never reassigned. Use 'const' instead.(prefer-const)"

2023-12-07 13:43 UTC, merged