test pull request (dont accept)
iqb-berlin/testcenter pull request #513
Opened 2024-04-25 10:37 UTC by nam-du-iqb

2024-05-02 13:48 UTC, nam-du-iqb commented
Resolves https://github.com/iqb-berlin/testcenter/issues/35

2024-05-07 12:07 UTC, paflov commented
Backend Unit tests schlagen fehl... https://scm.cms.hu-berlin.de/iqb/testcenter/-/jobs/216779

2024-05-08 14:51 UTC, nam-du-iqb commented
Unit Tests sind gefixt. GetSessions() benötigt nun einen Mock von WorkspaceDAO, da dieser beim Type="person" genutzt wird.

2024-05-15 08:48 UTC, paflov requested changes
Sehr gute Arbeit. Einen Wunsch hätte ich noch: Sie Ansicht sollte sich alle Sekunden aktualisieren.

2024-05-15 08:48 UTC, paflov commented on backend/src/data-collection/AccessSet.class.php
Ich denke es wäre vielleicht sauberer, anstatt einen zusätzlichen Parameter $workspaceName, die liste der $accessItems um einen geeigenten Typ zu erweitern (etwa WorkspaceData), und den workspace darüber mitzugeben.

2024-05-15 08:48 UTC, paflov commented on frontend/src/app/study-monitor/index.ts
sicher, dass wir das brauchen?

2024-05-16 12:07 UTC, nam-du-iqb commented on backend/src/data-collection/AccessSet.class.php
Stimme ich zu. Ich schaue mir an, inwiefern sich das potenzielle WorkspaceData von DataCollectionTypeSafe erben lässt.

2024-05-16 13:27 UTC, nam-du-iqb commented on backend/src/data-collection/AccessSet.class.php
Wurde so umgesetzt.

2024-05-28 09:59 UTC, paflov approved these changes

2024-05-28 10:00 UTC, merged