review new features
iqb-berlin/testcenter pull request #548
Opened 2024-05-28 14:47 UTC by nam-du-iqb

resolves #528

2024-07-15 13:23 UTC, paflov requested changes
So. Alos ich kam dank deinem gesquashe und mit dem code bestens klar, und habe auf Codeebene wenig bis nichts auszusetzen und konnte das jetzt doch viel schneller durchgehen als gedacht. Super gut, wir werdend as Testcenter zu neuen Höhen heben.

**Bugs**
- userAgent, originalUnitName und pageLabel werden zwar erfasst, tauchen aber im output (egal ob csv oder json) gar nicht auf!

**Verbesserungsvorschläge**
- Ich glaube, es wäre sinnvoll, nicht den ganzen userAgent auszugeben bzw, zu speichern, sondern nur die Kerninformation (browser + version, os+ version, ggf. gerät) in möglichst lesbarer form. Es gibt ne Menge Quirks mit diesem UserAgent (manche Browser geben einen falschen an usw.), der userAgent Service (frontend/src/app/shared/services/user-agent/user-agent.service.ts) und die Bibliotheken, die den verwenden, fangen schon eine Menge davon ab.
- Die Beschriftung des Buttons ("(Neue) Kommentare") finde ich nicht gut. Das klingt als läd man damit neue Kommentare herunter, nicht Kommentare in einem neuen Format. Es müsste schon "Kommentare (neues Format)" heißen... oder doch ein switch irgendwo oder so.

2024-07-15 13:25 UTC, paflov requested changes
Krass, dass das die Methode der Wahl ist, ein externes Keyboard festzustellen. ich würde mir wünschen, wenn du diese Sache in den MainDataService auslagern würdest oder, wenn es geht, auf einen Extra-Service oder so, und jedenfalls das Ergebnis im MainDataService speichern. Erstens wegen separation of concerns vor allem aber bin ich mir sicher, wir werden diese Information noch anderswo gut gebrauchen können

2024-08-15 11:49 UTC, paflov approved these changes

2024-08-15 11:56 UTC, paflov commented
Leider hab ich noch was:

**Bug**
* pageLabel wird zwar an den Server geschickt, aber nicht gespeichert

**Verbesserungsvorschläge**
* Neben dem Browser vllt doch schon das OS auch in das Feld schreiben
* das neue Format enthält ein Feld `"category_": "TRUE",` - das war schon ein Artefakt in dem alten und muss in dem neuen nicht enthalten sein, oder?
* in der JSON-Ausgabe strings mit "TRUE" und "FALSE" auszugeben anstatt booleans ist zumindest fragwürdig...

**Übrigens**
* leider testen die API-tests die JSON-Ausgabe nicht mit ab :/ ein weiterer Fail von Dredd.

2024-08-20 13:06 UTC, nam-du-iqb commented
- pagelabel wird jetzt gespeichert
- OS wird nun auch aus dem UserAgent gelesen
- ein leeres `"category_": "TRUE"` kann ich so gerade nicht mehr finden. Würde dies aber später entfernen, sollte dies replizierbar sein
- JSON und CSV geben jeweils ein anderes Format für boolean aus (true/false und "TRUE"/"FALSE")

2024-08-21 10:53 UTC, merged