move system check after login
iqb-berlin/testcenter pull request #580
Opened 2024-08-08 15:08 UTC by nam-du-iqb

resolves #352 

- three new intended values for the new field 'content_type' in the workspaces table (pre work for #570 )
-- 'test' can only show tests in their sessions
-- 'sysCheck' can only show sys-checks in their sessions
-- 'mixed' can do both
- introduce a new mode for Testtakers.xml : 'sys-check-login', if this mode is given to a login, the sys-check button disappears from the login menu (because the workspace content_type becomes either 'sysCheck' or 'mixed')
-- show the sys-check button after login, if the login session is within a workspace that has not the content_type 'test'
-- this new button shows the same sys-check starter page with all sys-checks of the whole instance

2024-08-15 12:15 UTC, paflov requested changes
Ich hoffe du nimmst es mir nicht übel, aber manches sollten wir noch mal überdenken glaube ich.

2024-08-15 12:15 UTC, paflov commented on scripts/database/patches.d/next.sql
Vllt besser enum als Feldtyp verwenden?

2024-08-15 12:15 UTC, paflov commented on frontend/src/app/app-root/starter/starter.component.ts
Wäre es nicht sinnvoller, die SysChecks als claims (bzw. AccessObjects aus Backendsicht) dem Object mitzugeben, das man bei getSession vom backend bekommt anstatt eine Parallelstruktur nebendran zu schaffen? Claims darf auch verschiedene Typen von Objekten enthalten, dort einen neuen Typ hinzuzufügen würde keinen API-Change bedeuten.

2024-08-15 12:15 UTC, paflov commented on backend/src/controller/SystemController.class.php
Ich bin mir ehrlich gesagt gar nicht so sicher, ob wir das noch brauchen? War das Teil der Absprache? Sonst würde ich die allgemein erreichbaren SysChecks komplett streichen der Vermeidung von Komplexität halber.

2024-08-22 12:19 UTC, nam-du-iqb commented on backend/src/controller/SystemController.class.php
Änderungen nach gemeinsamer Besprechung:
- nur der Login mit dem mode "sys-check-login" kann sich die Sys-Checks anzeigen lassen
- sys-checks werden gemeinsam mit den anderen accessObjects im GET /session abgerufen
- Der Klick auf Sys-Check Button im starter Menu führt direkt zur startseite des Checks ohne vorher auf die Übersichtsseite zu verweisen
- Das Label für die das sys-check password wurde für bessere Klarheit geändert

2024-08-26 09:23 UTC, merged

2024-09-27 09:38 UTC, tobhu1981 commented on backend/src/controller/SystemController.class.php
## Ergebnis Erprobung Login "sys-check-login" auf TC1 in V15.2.0
* sobald der ursprüngliche Gruppenname "sample_group" in der Testtaker, in der sich der neue Login `<Login mode="sys-check-login" name="sys-check" />` befindet, geändert wird, kommt eine 500er Meldung. Es ist also nicht möglich den Login in einer anderen Gruppe zu verwenden.