Feature/install script revision
iqb-berlin/testcenter pull request #641
Opened 2024-10-14 07:41 UTC by svwolter

2024-10-16 08:54 UTC, paflov requested changes

2024-10-16 08:54 UTC, paflov commented on config/frontend/nginx.conf
Diese Änderung verstehe ich nicht. Ich dachte wir packen alles, das in einen Service gehört in einen Ordner auf oberster Ebene?

2024-10-16 08:54 UTC, paflov commented on config/traefik/tls-config.yml
Damit müssten wir strenggenommen auch im Changelog fokumentieren, dass dieses vorher eingeführte Sicherheitsfeature nun wieder weg ist.

2024-10-16 08:54 UTC, paflov commented on dist-src/docker-compose.prod.tls.yml
Diese Änderung erfordert ein enprechendes migration script! Also der Pfad der certs Datei.

2024-10-16 14:30 UTC, svwolter commented on config/frontend/nginx.conf
Mein Ziel ist, möglichst geringe Abweichungen zur Produktion zu haben. Der Config-Ordner und der Secrets-Ordner bilden die Profuktionsumgebung 1:1 ab. So wird es später möglich sein, die Produktionsumgebung ohne zusätzlichen Aufwand jederzeit aus dem Repo heraus zu starten.

2024-10-17 08:46 UTC, paflov commented
Korrekte Rückmeldung bei blockierten Files steht noch aus?

2024-10-23 09:06 UTC, paflov requested changes
Task-Runner tasks funktionieren nicht mehr, z. B. make-docs - er findet das Gulpfile nicht. Irgendwelche Pfade stimmen nicht.

Mir ist auch aufgefallen, dass, wenn ich in der (übergeordneten) package.json was ändere, der task-runner davon nichts mitbekommt. Eventuell stimmt auch der pfad dazu in docker-compose.dev nicht, wobei er mir richtig aussieht.

2024-10-23 10:20 UTC, paflov commented
> docker image prune -a
> make init
> make build

Ja, jetzt geht es. Ich mache immer `make build` wenn ich den branch wechsle, aber anscheinend baut er dann den taskrunner nicht mit neu. darauf bin ich nicht gekommen.

2024-10-23 12:22 UTC, merged